name: Build Windows EXE with Premium Installer

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: society_user
        run: flutter pub get

      - name: Build Windows Executable
        working-directory: society_user
        run: flutter build windows --release

      - name: Compile Inno Setup Script
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: society_user/windows/installer/installer_script.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartGateBD-Installer-Windows
          path: society_user/build/windows/x64/runner/Release/Dalan-Installer.exe
